### PR TITLE
Multiply

### PR DESCRIPTION
**Pull request by jillianw**

### CODE REVIEW

**Comment by sumeetjain** [comment]
Looks good so far. I'll wait for the def/end part.

As for not being able to put this together off the top of your head, don't worry about that just yet. Even wizened old programmers spend half their day googling for things.

> Never memorize something that you can look up.
> – Albert Einstein

**Comment by jillianw** [comment]
(I submitted this via Cloud 9 but updates aren't showing up in GitHub after push so here's a copy/paste....)

``` ruby
def this_array(a, b)
  this_array = Array.new(b) {a}
  sum = 0
  this_array.each do |add_numbers|
    sum += add_numbers
end

print "Enter a number: "
a = gets.chomp

print "Enter another number: "
b = gets.chomp

puts this_array
```

Broken code here. The example of how to write a method in bastards book was too simple for me to apply it to what I'm trying to do here, so I found this example:

http://www.dev-hq.net/ruby/8--creating-methods

I used the one toward the bottom of the page about adding two numbers. I tweaked it using the code I had already submitted but something is busted... Got any suggestions?

**Comment by sumeetjain** [comment]
Your code below is very close. I'll paste it for reference here and then below it I have a few pointers.

``` ruby
def this_array(a, b)
  this_array = Array.new(b) {a}
  sum = 0
  this_array.each do |add_numbers|
    sum += add_numbers
end
```

### 1. Indentation

Give this a read: https://github.com/omahacodeschool/wiki/blob/master/ruby/indentation.md

It should expose a missing `end` in your code, which is causing an error currently.

### 2. Cloud9 Troubles

Are you sure you're saving the file? If you make changes to the file and then go to the **File** menu (where the **Save** option is located), are you able to save the file? So far, students forgetting to do this has been the most common cause of Cloud9 issues.

### 3. Return Value

Your method follows a very common pattern: Start with a zero/empty variable and modify it mechanically in your algorithm. That is, you start with `sum = 0` and modify it with `sum += add_numbers`. That's a good algorithm. The missing piece however, is that the very last line of your method (Well, right before the _final_ `end`) should be `return sum`. Otherwise, your method does the work of modifying `sum`, but it doesn't provide that value in the end.

**Comment by jillianw** [comment]
Hi Sumeet -

I'm still not sure that Cloud9 is working for me. I've been saving my files, but this one, I think, is still not coming through. This is the message I get in Cloud9 after git push (I haven't looked close enough at other messages to know if this is different than usual):

screen shot 2016-01-18 at 9 17 03 am

Anyhow, this is what I submitted:

screen shot 2016-01-18 at 9 28 21 am

I think I got the missing "end" in the right place because I'm not getting that error any more. I'm thinking I still need to have something like this at the end, right?

print "Enter a number: "
a = gets.chomp

print "Enter another number: "
b = gets.chomp

Otherwise, how are a and b going to be defined? However, the results Ruby is giving me are just the value entered for b, not b \* a. I don't understand what I'm doing wrong.

**Comment by sumeetjain** [comment]
Can you rename the method back to `multiply` (instead of `this_array`)? That should help, because the tests that run expect the method's name to not have changed. (Sorry–I should have made this clearer before.)

You don't need any `puts` or `gets` or things like that. The test provides values for `a` and `b`.

**Comment by sumeetjain** [comment]
:+1:

**Pull request closed without merging**
