### PR TITLE
Done

### PR DESCRIPTION
**Pull request by wig-wig**
Not sure if I did this correctly or not???

Are you looking for specific path to the integer 30 or is my method of joining the numbers, reversing them, and calling the first two as an integer thus returning 30 acceptable?

### CODE REVIEW

**Comment by sumeetjain** [comment]
Just commenting so you know I've seen this. I'm assuming you'll re-try it based on my comment about your reverse-string toy problem. (Again, my apologies for the confusion.)

**Comment by wig-wig** [comment]
Yep yep.

**Comment by sumeetjain** [comment]
Nice! This is approvable, but I'd like you to please correct the indentation of the code first. (This doesn't affect the functionality of the code, but it's still important–so I'm having students do this to begin building that habit.)

**Comment by sumeetjain** [comment]
:+1: I'm approving this, but the indentation should like this:

``` ruby
def multiply(num1, num2)
    new_a = [ ]
    (num1).times do |i|  
        new_a << (num2)
    end

    return new_a.inject { |sum,x| sum + x }
end
```

It can be hard to deduce what correct indentation is, so I felt that a valid example would be more useful than me just saying, "No try again!" :) Notice how indentation is caused by lines of code that aren't "done" by their last line's character.

For example, `def multiply(num1, num2)` isn't "done" until the `end` at the very bottom–so that must mean that everything after it, but before its `end` is indented. And `(num1).times do |i|` isn't "done" until _its_ `end`–same effect.

**Pull request closed without merging**
