### PR TITLE
Multiply

### PR DESCRIPTION
**Pull request by CatalystCoder**

### CODE REVIEW

**Comment by sumeetjain** [comment]
This is very close. The thing about methods is that they're basically two things in one:
1. They **do** some operations (like adding this to that and collecting these things and looping over them, etc, etc).
2. After those operations are done, they **return** a single value. And you can specify that return value.

For example, here is a method that does a bunch of stuff and then returns something completely unrelated:

``` ruby
def example_method(input)
  x = input * 100
  cost_per_item = x / 50
  tax_per_item = cost_per_item * 0.085
  return "Hey what's up Tyler?"
end
```

That last line is the "return value" of the method. So if you executed the method like `example_method(20)`, then all that math would happen–but behind the scenes–and when it was finished, Ruby would output `"Hey what's up Tyler?"`.

Your method is failing because it's not giving a meaningful return value. See if you can work through adding a return value to your method, and don't hesitate to ask for clarification of the above.

**Comment by CatalystCoder** [comment]
Okay I see what you mean. Last night when I ran rake it came back with the green dot at first. I'll go ahead and get it fixed and place the final product on here or I can resubmit it. Shouldn't take me too long!

**Comment by CatalystCoder** [comment]
okay so when I ran this it seemed to work. Let me know if it looks right! 

def multiply(num1, num2)
    output = 0
    for i in 1..num2
        output = output + num1 
    end
    return output
end

I resubmitted the code once I got a confirmation that it worked in it's entirety! :)

**Comment by sumeetjain** [comment]
:+1:

**Pull request closed without merging**
